project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /Iconify/app/src/main/res/values/strings.xml
    translation: /Iconify/app/src/main/res/values-%android_code%/%original_file_name%