name: Crowdin Upload

on:
  push:
    branches:
      - 'beta'

jobs:

  synchronize-with-crowdin:
    name: Upload strings to Crowdin
    if: github.repository_owner == 'Mahmud0808'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Strings
        uses: crowdin/github-action@v1
        with:
          upload_translations: false
          upload_sources: true
          download_translations: false
          localization_branch_name: beta
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}